<?php

/** @noinspection PhpUndefinedVariableInspection */

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use BuzzingPixel\Templating\TemplateEngine;
use MissionControlBackend\Templating\VendorCss;
use MissionControlBackend\Templating\VendorJs;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

$title ??= '';

?>

<!doctype html>
<html lang="en" class="h-full bg-gray-50">
<head>
    <title>
        <?php if ($title !== '') : ?><?=$title?> | <?php endif; ?>Mission Control
    </title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php if (VendorCss::hasVendorPaths()) : ?>
        <?php foreach (VendorCss::vendorPaths() as $vendorPath) : ?>
            <link
                rel="stylesheet"
                href="<?= $vendorPath ?>"
            >
        <?php endforeach

 ?>
    <?php endif ?>
    <?php if ($this->hasSection('headContent')) : ?>
        <?= $this->getSection('headContent') ?>
    <?php endif ?>
</head>
<body class="h-full">
    <?= $this->getSection('layoutContent') ?>
    <?php if (VendorJs::hasVendorPaths()) : ?>
        <?php foreach (VendorJs::vendorPaths() as $vendorPath) : ?>
            <script
                src="<?= $vendorPath ?>"
                type="text/javascript"
            ></script>
        <?php endforeach

 ?>
    <?php endif ?>
    <?php if ($this->hasSection('footContent')) : ?>
        <?= $this->getSection('footContent') ?>
    <?php endif ?>
</body>
