<?php

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use Qiq\Template;

/** @phpstan-ignore-next-line */
assert($this instanceof Template);

$title ??= '';

?>

<!doctype html>
<html lang="en" class="h-full bg-gray-50">
<head>
    <title><?php if ($title !== '') : ?><?=$title?> | <?php endif; ?>Mission Control</title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="h-full">
    <?php /** @phpstan-ignore-next-line */ ?>
    <?= $this->getContent() ?>
</body>
