<?php

/** @noinspection PhpUndefinedVariableInspection */

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use BuzzingPixel\Templating\TemplateEngine;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

$title ??= '';

?>

<!doctype html>
<html lang="en" class="h-full bg-gray-50">
<head>
    <title>
        <?php if ($title !== '') : ?><?=$title?> | <?php endif; ?>Mission Control
    </title>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="h-full">
    <?= $this->getSection('layoutContent') ?>
    <?php if ($this->hasSection('react-script')) : ?>
        <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
        <?= $this->getSection('react-script') ?>
    <?php endif ?>
</body>
